apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 3 # El número de réplicas que deseas ejecutar
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: deployhome:TAG
        ports:
        - containerPort: 8081 # El puerto en el que se ejecuta tu aplicación
