apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 3 # El número de réplicas que deseas ejecutar
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: deployhome:TAG
        ports:
        - containerPort: 8181 # El puerto en el que se ejecuta tu aplicación
